version: "3"
services:
        jupyter:
                image: jupyter/scipy-notebook
                container_name: "my_jupyter"
                ports:
                        - 8888:8888
                #volumes:
                        #- ./jupyternotebooks/:/home/jovyan/
        superset:
                image: tylerfowler/superset
                container_name: "my_superset"
                ports:
                        - 8088:8088
        pgweb:
                image: sosedoff/pgweb
                container_name: "my_pgweb"
                ports:
                        - 8081:8081
        postgres:
                image: postgres
                container_name: "my_postgres"
                ports:
                        - 5432:5432
                environment:
                        - SHARED_PASSWORD=password
                        - POSTGRES_PASSWORD=secret
                volumes:
                        - ./dbscripts/:/docker-entrypoint-initdb.d/
                        - pg_data:/var/lib/postgresql/data
        minio:
                image: minio/minio
                container_name: "my_minio"
                ports:
                        - 9000:9000
                environment:
                        - MINIO_ACCESS_KEY=12345678
                        - MINIO_SECRET_KEY=password
                command: server /data
volumes:
        pg_data:              
